version: '3'

services:
  foxdex:
    image: coinflow/lend-api:latest
    container_name: lend
    restart: always
    ports:
      - "8080:9701"
    privileged: true

  web:
    image: coinflow/lend-web:latest
    container_name: web
    restart: always
    ports:
      - "8000:80"
    privileged: true


networks:
  lend_default:
    driver: bridge