version: '3'

services:
  lend:
    image: coinflow/lend-api:dev
    container_name: lend
    restart: always
    ports:
      - "9701:9701"
    privileged: true

  web:
    image: coinflow/lend-web:dev
    container_name: web
    restart: always
    ports:
      - "8080:80"
    privileged: true


networks:
  ableo_default:
    driver: bridge