version: '3'

services:
  lend:
    image: coinflow/lend-api:dev
    volumes:
    -  /home/ubuntu/lendApiConfig:/usr/src/app/config
    environment:
      - NODE_ENV=production
    container_name: lend
    restart: always
    ports:
      - "8081:9701"
    privileged: true
    tty: true
  web:
    image: coinflow/lend-web:dev
    container_name: web
    restart: always
    ports:
      - "8080:80"
    privileged: true

networks:
  lend_default:
    driver: bridge

