version: '3'

services:
  lend:
    environment:
      - NODE_ENV=production
    image: coinflow/lend-api:latest
    container_name: lend
    volumes:
      - /home/ubuntu/lendApiConfig:/usr/src/app
    restart: always
    ports:
      - "8080:9701"
    privileged: true

  web:
    image: coinflow/lend-web:latest
    container_name: web
    restart: always
    ports:
      - "80:80"
    privileged: true


networks:
  lend_default:
    driver: bridge