version: '3'

services:
  lend:
    image: coinflow/lend-api:dev
#    environment:
#      - NODE_ENV='development'
    container_name: lend
    restart: always
    volumes:
      - /data:/var/data
    ports:
      - "8081:9701"
    privileged: true
    tty: true
  web:
    image: coinflow/lend-web:dev
    container_name: web
    restart: always
    ports:
      - "8080:80"
    privileged: true


networks:
  lend_default:
    driver: bridge